---
- name: Update all packages
  yum:
    name: '*'
    state: latest
    update_cache: yes
    exclude: kernel

- name: Install EPEL
  yum:
    name: epel-release
    state: latest
    update_cache: yes

- name: Install troubleshooting tools
  yum:
    name:
    - procps-ng
    - sysstat
    - iotop
    - htop
    - atop
    - strace
    - ltrace
    - gdb
    state: latest
    update_cache: yes

- name: Enable service atop
  systemd:
    name: atop
    enabled: yes
    masked: no

- name: Start service atop
  service:
    name: atop
    state: started

- name: Generate atop config file
  template:
    src: atop.j2
    dest: /etc/sysconfig/atop
  notify: Restart atop
